---
  - include_tasks: redhat.yml
    when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'
  
  - include_tasks: amazon-linux.yml
    when: ansible_distribution == 'Amazon'
  
  - include_tasks: debian.yml
    when: ansible_os_family == 'Debian'
