---
  - name: Install ntp
    package:
      name: ntp
      state: present
  
  - name: enable ntpd service
    service:
      name: ntpd
      enabled: true
  
  # - name: disable default pool
  #   lineinfile:
  #     dest: /etc/ntp.conf
  #     regexp: '^pool .*ubuntu'
  #     state: absent
  #     backup: true
  
  # - name: set pool
  #   lineinfile:
  #     dest: /etc/ntp.conf
  #     line: "pool {{ ntp_pool_server }} iburst"
  #     backup: true
  #   notify:
  #     - restart ntp
