---
- name: Install nginx
  package: name=nginx state=present

- name: Delete default configuration
  file: path=/etc/nginx/conf.d/{{ item }} state=absent
  with_items:
    - default.conf
    - example_ssl.conf

- name: Copy nginx base configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Copy nginx fallback configuration
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  when: nginx_reject_unexpected_server_name == true

- name: Copy nginx configuration for Drupal
  template: src=drupal.conf.j2 dest={{ nginx_vhost_path }}/{{ nginx_server_name }}.conf
  notify: restart nginx

- name: Enable nginx service
  command: systemctl enable nginx

