---
- include_tasks: centos.yml
  become: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- include_tasks: redhat.yml
  become: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'RedHat'

- include_tasks: amazon-linux.yml
  become: yes
  when: ansible_distribution == 'Amazon'

- include_tasks: debian.yml
  become: yes
  when: ansible_os_family == 'Debian'

- block:
  - name: Check if php-fpm is enabled
    command: systemctl is-enabled php-fpm
    register: php_fpm_is_enabled
    changed_when: False
    ignore_errors: True # FIXME

  - block:
      - name: Change owner for session directory
        file:
          path: "{{ php_fpm_php_session_save_path }}"
          group: "{{ php_fpm_group }}"
          owner: "{{ php_fpm_user }}"
        when: php_fpm_php_session_save_handler == "files"
      
      - name: Enable php-fpm
        command: systemctl enable php-fpm
    become: yes
    when: php_fpm_is_enabled.stdout == "disabled"

  - name: Copy php-fpm configuration
    template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf
    notify: restart php-fpm
    become: yes
  when: ansible_distribution != 'RedHat'
