---
- name: Enable remi repository
  package: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: Enable remi repo for PHP 5.6.
  set_fact: php_enablerepo="remi-php56"
  when: php_version == "5.6"

- name: Enable remi repo for PHP 7.0.
  set_fact: php_enablerepo="remi-php70"
  when: php_version == "7.0"

- name: Enable remi repo for PHP 7.1.
  set_fact: php_enablerepo="remi-php71"
  when: php_version == "7.1"

- name: Enable remi repo for PHP 7.2.
  set_fact: php_enablerepo="remi-php72"
  when: php_version == "7.2"

- name: Install php-fpm and deps 
  package: name={{ item }} state=present enablerepo={{ php_enablerepo }}
  with_items:
    - php
    - php-cli
    - php-mbstring
    - php-fpm
    - php-xml
    - php-gd
    - php-mysqlnd
    - php-json
    - php-mcrypt
    - php-ldap
    - php-opcache
    - php-apcu
