---
- name: Install Drupal environment
  hosts: all

  vars_files:
    - config.yml

  roles:
    - { role: timezone, tags: [ base ] }
    - { role: ntp, tags: [ base ] }
    - { role: swap, tags: [ base ] }
    - { role: selinux, tags: [ base ] }
    - { role: yum_cron, tags: [ base ] }
    - { role: firewalld, tags: [ base ] }
    - { role: common, tags: [ base, app ] }
    - { role: nginx, tags: [ app ] }
    - { role: php-fpm, tags: [ app ] }
    - { role: composer, tags: [ app ] }
    - { role: mysql, tags: [ app ] }
    - { role: drush, tags: [ app ] }
    - { role: drupal, tags: [ app ] }
    - { role: awscli, tags: [ base ] }
    #- { role: nodejs, tags: [ optional ] }
    #- { role: openjdk, tags: [ optional ] }
    #- { role: solr4drupal, tags: [ optional ] }
    - { role: cron, tags: [ optional ] }
