---
- name: Install python-pip
  package: name={{ item }} state=present
  with_items:
    - python-pip

- name: Install awscli
  pip:
    name: awscli

- name: Create the awscli config directory
  file: >
    path={{ ansible_env.HOME}}/.aws
    state=directory
    mode=0700

- name: Create awscli config
  template: >
    src=config.j2
    dest={{ ansible_env.HOME }}/.aws/config
    mode=0600
  when: aws_output_format is defined and aws_region is defined

- name: Create awscli credentials
  template: >
    src=credentials.j2
    dest={{ ansible_env.HOME }}/.aws/credentials
    mode=0600
  when: aws_access_key_id is defined and aws_secret_access_key is defined
