---
- name: Install Mysql package
  package: name={{ item }} state=present
  with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb

- name: Copy server config
  template: src=server.cnf.j2 dest=/etc/mysql/mysql.conf.d/mysqld.cnf owner=root mode=0644
- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
