---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'

- include_tasks: amazon-linux.yml
  when: ansible_distribution == 'Amazon'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Update MySQL root password
  mysql_user:
    host: localhost
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root

- name: copy .my.cnf
  template: src=.my.cnf.j2 dest="/home/{{ lookup('env','USER') }}/.my.cnf" owner="{{ lookup('env','USER') }}" mode=0600

- name: update password in .my.cnf
  lineinfile:
    dest: "/home/{{ lookup('env','USER') }}/.my.cnf"
    state: present
    regexp: "^password =*"
    line: "password = {{ mysql_root_password }}"
    backrefs: yes
