---
- include_tasks: redhat.yml
  become: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'

- include_tasks: amazon-linux.yml
  become: yes
  when: ansible_distribution == 'Amazon'

- include_tasks: debian.yml
  become: yes
  when: ansible_os_family == 'Debian'

- name: copy .my.cnf
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  become: yes

- name: Update MySQL root password
  mysql_user:
    host: localhost
    name: root
    password: "{{ mysql_root_password }}"
  become: yes

- name: update password in .my.cnf
  lineinfile:
    dest: /root/.my.cnf
    state: present
    regexp: "^password =$"
    line: "password = {{ mysql_root_password }}"
    backrefs: yes
  become: yes
