---
- name: Install firewalld
  package: name=firewalld state=present

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: Setup firewalld
  firewalld: port={{ item }} permanent=true zone={{ firewalld_zone }} state=enabled
  with_items: "{{ firewalld_allowed_ports }}"

- name: Reload firewalld
  command: firewall-cmd --reload

- name: Enable firewalld
  command: systemctl enable firewalld
